### ISSUE TITLE
Publish APK on Github?

### ISSUE THREAD

**Issue by IzzySoft** [RajneeshSingh007/MusicX-Music-Player#2]
Did you consider publishing the `.apk` at Github (best place: create a tag for each release and attach it there, on the `releases/` page – see [Creating Releases](https://help.github.com/articles/creating-releases/)?

**Comment by IzzySoft** [comment]
Hm, just closed and no comment? I take it that should mean "no" then? A pity for an open source app if it's only available in a closed market ;)

**Comment by RajneeshSingh007** [comment]
@IzzySoft from today i'm going to release app on github ,so i released latest version and closed. I thought you will watch in the release section 😀

**Comment by IzzySoft** [comment]
@RajneeshSingh007 That was indeed were I looked before commenting again, but it wasn't (yet) there. Thanks for your feedback, so I'll check again a little later :smiley_cat:

**Comment by IzzySoft** [comment]
@RajneeshSingh007 May I bring up the topic again, as the `.apk` file is still missing in the `releases/` page?

**Comment by RajneeshSingh007** [comment]
Just now checked and fixed the issue, Thanks a lot :)

Best Regards,
Rajneesh Singh

On May 18, 2017 3:51 PM, "Izzy" <notifications@github.com> wrote:

@RajneeshSingh007 <https://github.com/rajneeshsingh007> May I bring up the
topic again, as the .apk file is still missing in the releases/ page?

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/RajneeshSingh007/MusicX-Music-Player/issues/2#issuecomment-302364023>,
or mute the thread

**Comment by IzzySoft** [comment]
Thanks a lot! You can now also find it [here](https://apt.izzysoft.de/fdroid/index/apk/com.rks.musicx), to be used via the F-Droid client to install/update your app. Feel free linking to it :smiley_cat:

**Comment by islamnafea** [comment]
@RajneeshSingh007 
Wonderful work from a great person like you but I hope you want to know how to add ads Admob
